### PR TITLE
fix array decl

### PR DESCRIPTION
**Pull request by jdonaldson**
array declarations don't seem to work right.  E.g. if you try:
```haxe
trace([1,2,3]);
```
you get:

```
2, 1, 3
```

Assigning the array directly seems to work just fine, any reason not to do that?

### CODE REVIEW

**Comment by PeyTy** [comment]
@jdonaldson 
Little explanation:
With `[0]=`:
`[0]=1 [1]=2 [2]=3` From zero index just like in Haxe!
Without:
`[1]=1 [2]=2 [3]=3` Lua arrays` indexed from one.

**My fix works perfectly in Lua JIT** but fails on plain Lua. I was hoping that this crap does not going to happen.

**If you *can* just use Lua JIT 2 VM**, it is *much* more stable in terms of tables behavior.
I recomend to use it with disabled jit `-joff` (because of some rare segfaults)

I`ll try to make quick fix now.

**Comment by PeyTy** [comment]
```Haxe
var a = [1,2,3];
trace([1,2,3]); // prints [ 2, 3, 1 ]
trace(a); // prints [ 2, 3, 1 ]
trace(a[0], a[1], a[2]); // prints 1,2,3
```

**Comment by PeyTy** [comment]
Fix:
```Haxe
var a = [1,2,3,null,5];
trace([1,2,3]); // prints [ 1, 2, 3 ]
trace(a); // prints [ 1, 2, 3, null, 5 ]
trace(a[0], a[1], a[2]); // prints 1,2,3
trace("" + a); // prints [ 1, 2, 3, null, 5 ]
```
Little slower, but guaranteed to work as expected.

**Comment by jdonaldson** [comment]
gotcha.  Thanks for the details.

**Pull request closed without merging**
