### PR TITLE
moving class files to src folders, fixing list issues, fixing test issue...

### PR DESCRIPTION
**Pull request by jdonaldson**
Here's a bit of work, I started to try and patch things in smaller pieces, but I at least wanted to get a working unit test runner so we can avoid breaking stuff.  To do that I had to fix:

1. fix the list iterator
2. add a custom test runner class
3. move all of the haxe source to a src dir, along with tests.  (also, update haxelib.json with a classpath)
4. fix Type behavior, as well as Reflect

I was just trying to write a stupid test for StringTools.isEof, and this is where I ended up.  The final issue is that it doesn't seem to be possible to override inline methods in std core apis.  I had to use a --no-inline method, and I would strongly recommend that get added to extraParams.hxml if I'm correct.  More details in the files.

### CODE REVIEW

**Comment by PeyTy** [comment]
@jdonaldson 
Befor I read your changes, I may mentions that https://github.com/PeyTy/haxe-codegenerators-tests is being used for testing purposes.
So many changes, mind blowing)
*went reading comments*

**Comment by PeyTy** [comment]
@jdonaldson Sorry, I can not accept your PR "as is". I will copy parts of the code from PR and add you to contributors list. Is this OK for you?

Expecially, please, dont change directory structure, file-renaming etc. This breaks my local unsynced changes and makes the code looks... weird for me Oo

**Comment by jdonaldson** [comment]
Yeah, maybe there were too many changes for one go.  Still, there's a lot of work to do here.  Having a clean directory structure is usually what I do first.  It's a good idea to have source code separate from other miscellaneous code  like readmes, hxml, and other metadata.  I think it's also nice to make the tests an obvious and crucial part of the lib.  It'll make it easier to write test automation (using [travis](http://travis-ci.org), and it'll make it clearer to contributors how to test their changes.

Not having all of that for a complicated library (like a platform generator) is a big warning sign to me.  The other thing that's highly concerning is the fact that you're describing this library as "fully functional" in the readme.  You've done some nice work here, but you can't claim that yet.

**Comment by PeyTy** [comment]
@jdonaldson Good thoughts. "Fully functional" meant for pre-alpha version. Typically, such a code (pre-alpha), even compile is not possible, but this project people have even used for commercial development.

**Pull request closed without merging**
